name: mobile
description: "CozyTalk - A cozy chat application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_database: ^12.3.0
  cloud_functions: ^6.2.0

  # Auth
  google_sign_in: ^7.2.0
  flutter_secure_storage: ^10.0.0

  # State management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # Navigation
  go_router: ^17.2.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  cryptography: ^2.7.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^4.0.3
  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.13.0

dependency_overrides:
  test_api: 0.7.10
  path_provider_foundation: 2.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/moods/
    - assets/images/dressup/
    - assets/images/backgrounds/
