// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhEm1tJRomLx7ErcaHDYSlnyrpchgmro8',
    appId: '1:170726022216:web:953700049a0d5f5e700c7d',
    messagingSenderId: '170726022216',
    projectId: 'cozytalk-5d984',
    authDomain: 'cozytalk-5d984.firebaseapp.com',
    databaseURL:
        'https://cozytalk-5d984-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cozytalk-5d984.firebasestorage.app',
    measurementId: 'G-YE9986EL8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0uL81GiUOwFTpXduSvGcge_8X86DepXw',
    appId: '1:170726022216:android:932eeaa1e0193646700c7d',
    messagingSenderId: '170726022216',
    projectId: 'cozytalk-5d984',
    authDomain: 'cozytalk-5d984.firebaseapp.com',
    databaseURL:
        'https://cozytalk-5d984-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cozytalk-5d984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJMtaW2bKkKvC7kqI15F1p9R5bPV8t2BA',
    appId: '1:170726022216:ios:8eb3c39d2006fd8b700c7d',
    messagingSenderId: '170726022216',
    projectId: 'cozytalk-5d984',
    databaseURL:
        'https://cozytalk-5d984-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cozytalk-5d984.firebasestorage.app',
    iosClientId:
        '170726022216-9lurnom76eqbeortib0tps3kbk215sj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJMtaW2bKkKvC7kqI15F1p9R5bPV8t2BA',
    appId: '1:170726022216:ios:8eb3c39d2006fd8b700c7d',
    messagingSenderId: '170726022216',
    projectId: 'cozytalk-5d984',
    databaseURL:
        'https://cozytalk-5d984-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cozytalk-5d984.firebasestorage.app',
    iosClientId:
        '170726022216-9lurnom76eqbeortib0tps3kbk215sj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhEm1tJRomLx7ErcaHDYSlnyrpchgmro8',
    appId: '1:170726022216:web:75564ef4321736b8700c7d',
    messagingSenderId: '170726022216',
    projectId: 'cozytalk-5d984',
    authDomain: 'cozytalk-5d984.firebaseapp.com',
    databaseURL:
        'https://cozytalk-5d984-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cozytalk-5d984.firebasestorage.app',
    measurementId: 'G-QL1XQ4EG20',
  );
}
